---
name: Tests macOS
permissions: read-all
on: [push, pull_request]
jobs:
  test-macos:
    strategy:
      fail-fast: false
      matrix:
        target:
          - macos-unit-test-4-cpu
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: .go-version
      - env:
          TARGET: ${{ matrix.target }}
        run: |
          case "${TARGET}" in
            macos-unit-test-4-cpu)
              CPU=4 make test
              ;;
            macos-unit-test-4-cpu-race)
              CPU=4 ENABLE_RACE=true make test
              ;;
            *)
              echo "Failed to find target"
              exit 1
              ;;
          esac

  test-macos-race:
    strategy:
      fail-fast: false
      matrix:
        target:
          - macos-unit-test-4-cpu-race
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: .go-version
      - env:
          TARGET: ${{ matrix.target }}
        run: |
          case "${TARGET}" in
            macos-unit-test-4-cpu-race)
              CPU=4 ENABLE_RACE=true make test
              ;;
            *)
              echo "Failed to find target"
              exit 1
              ;;
          esac
